// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.26.1
// source: Builder.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferDirection int32

const (
	TransferDirection_INTO  TransferDirection = 0
	TransferDirection_OUTOF TransferDirection = 1
)

// Enum value maps for TransferDirection.
var (
	TransferDirection_name = map[int32]string{
		0: "INTO",
		1: "OUTOF",
	}
	TransferDirection_value = map[string]int32{
		"INTO":  0,
		"OUTOF": 1,
	}
)

func (x TransferDirection) Enum() *TransferDirection {
	p := new(TransferDirection)
	*p = x
	return p
}

func (x TransferDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_Builder_proto_enumTypes[0].Descriptor()
}

func (TransferDirection) Type() protoreflect.EnumType {
	return &file_Builder_proto_enumTypes[0]
}

func (x TransferDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferDirection.Descriptor instead.
func (TransferDirection) EnumDescriptor() ([]byte, []int) {
	return file_Builder_proto_rawDescGZIP(), []int{0}
}

// Standard input/output.
type Stdio int32

const (
	Stdio_STDIN  Stdio = 0
	Stdio_STDOUT Stdio = 1
	Stdio_STDERR Stdio = 2
)

// Enum value maps for Stdio.
var (
	Stdio_name = map[int32]string{
		0: "STDIN",
		1: "STDOUT",
		2: "STDERR",
	}
	Stdio_value = map[string]int32{
		"STDIN":  0,
		"STDOUT": 1,
		"STDERR": 2,
	}
)

func (x Stdio) Enum() *Stdio {
	p := new(Stdio)
	*p = x
	return p
}

func (x Stdio) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stdio) Descriptor() protoreflect.EnumDescriptor {
	return file_Builder_proto_enumTypes[1].Descriptor()
}

func (Stdio) Type() protoreflect.EnumType {
	return &file_Builder_proto_enumTypes[1]
}

func (x Stdio) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stdio.Descriptor instead.
func (Stdio) EnumDescriptor() ([]byte, []int) {
	return file_Builder_proto_rawDescGZIP(), []int{1}
}

// Build error type.
type BuildErrorType int32

const (
	BuildErrorType_BUILD_FAILED BuildErrorType = 0
	BuildErrorType_INTERNAL     BuildErrorType = 1
)

// Enum value maps for BuildErrorType.
var (
	BuildErrorType_name = map[int32]string{
		0: "BUILD_FAILED",
		1: "INTERNAL",
	}
	BuildErrorType_value = map[string]int32{
		"BUILD_FAILED": 0,
		"INTERNAL":     1,
	}
)

func (x BuildErrorType) Enum() *BuildErrorType {
	p := new(BuildErrorType)
	*p = x
	return p
}

func (x BuildErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_Builder_proto_enumTypes[2].Descriptor()
}

func (BuildErrorType) Type() protoreflect.EnumType {
	return &file_Builder_proto_enumTypes[2]
}

func (x BuildErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildErrorType.Descriptor instead.
func (BuildErrorType) EnumDescriptor() ([]byte, []int) {
	return file_Builder_proto_rawDescGZIP(), []int{2}
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_Builder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Builder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_Builder_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_Builder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Builder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_Builder_proto_rawDescGZIP(), []int{1}
}

type LookupContextRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Lowercase hexadecimal SHA-256 digest of the context tar stream.
	Digest        string `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupContextRequest) Reset() {
	*x = LookupContextRequest{}
	mi := &file_Builder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupContextRequest) ProtoMessage() {}

func (x *LookupContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Builder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupContextRequest.ProtoReflect.Descriptor instead.
func (*LookupContextRequest) Descriptor() ([]byte, []int) {
	return file_Builder_proto_rawDescGZIP(), []int{2}
}

func (x *LookupContextRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type LookupContextResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the unpacked context is available in the local cache.
	Present       bool `protobuf:"varint,1,opt,name=present,proto3" json:"present,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupContextResponse) Reset() {
	*x = LookupContextResponse{}
	mi := &file_Builder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupContextResponse) ProtoMessage() {}

func (x *LookupContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Builder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupContextResponse.ProtoReflect.Descriptor instead.
func (*LookupContextResponse) Descriptor() ([]byte, []int) {
	return file_Builder_proto_rawDescGZIP(), []int{3}
}

func (x *LookupContextResponse) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

type CreateBuildRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the build stage.
	StageName string `protobuf:"bytes,1,opt,name=stage_name,json=stageName,proto3" json:"stage_name,omitempty"`
	// The tag of the image to be created.
	Tag string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	// Any additional metadata to be associated with the build.
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Additional build arguments.
	BuildArgs []string `protobuf:"bytes,4,rep,name=build_args,json=buildArgs,proto3" json:"build_args,omitempty"`
	// Enable debug logging.
	Debug         bool `protobuf:"varint,5,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBuildRequest) Reset() {
	*x = CreateBuildRequest{}
	mi := &file_Builder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuildRequest) ProtoMessage() {}

func (x *CreateBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Builder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBuildRequest.ProtoReflect.Descriptor instead.
func (*CreateBuildRequest) Descriptor() ([]byte, []int) {
	return file_Builder_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBuildRequest) GetStageName() string {
	if x != nil {
		return x.StageName
	}
	return ""
}

func (x *CreateBuildRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *CreateBuildRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateBuildRequest) GetBuildArgs() []string {
	if x != nil {
		return x.BuildArgs
	}
	return nil
}

func (x *CreateBuildRequest) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

type CreateBuildResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique ID for the build.
	BuildId string `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	// Any additional metadata to be associated with the build.
	Metadata      map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBuildResponse) Reset() {
	*x = CreateBuildResponse{}
	mi := &file_Builder_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuildResponse) ProtoMessage() {}

func (x *CreateBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Builder_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBuildResponse.ProtoReflect.Descriptor instead.
func (*CreateBuildResponse) Descriptor() ([]byte, []int) {
	return file_Builder_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBuildResponse) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *CreateBuildResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ClientStream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique ID for the build.
	BuildId string `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	// The packet type.
	//
	// Types that are valid to be assigned to PacketType:
	//
	//	*ClientStream_Signal
	//	*ClientStream_Command
	//	*ClientStream_BuildTransfer
	//	*ClientStream_ImageTransfer
	PacketType    isClientStream_PacketType `protobuf_oneof:"packet_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientStream) Reset() {
	*x = ClientStream{}
	mi := &file_Builder_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStream) ProtoMessage() {}

func (x *ClientStream) ProtoReflect() protoreflect.Message {
	mi := &file_Builder_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStream.ProtoReflect.Descriptor instead.
func (*ClientStream) Descriptor() ([]byte, []int) {
	return file_Builder_proto_rawDescGZIP(), []int{6}
}

func (x *ClientStream) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *ClientStream) GetPacketType() isClientStream_PacketType {
	if x != nil {
		return x.PacketType
	}
	return nil
}

func (x *ClientStream) GetSignal() *Signal {
	if x != nil {
		if x, ok := x.PacketType.(*ClientStream_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

func (x *ClientStream) GetCommand() *Run {
	if x != nil {
		if x, ok := x.PacketType.(*ClientStream_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ClientStream) GetBuildTransfer() *BuildTransfer {
	if x != nil {
		if x, ok := x.PacketType.(*ClientStream_BuildTransfer); ok {
			return x.BuildTransfer
		}
	}
	return nil
}

func (x *ClientStream) GetImageTransfer() *ImageTransfer {
	if x != nil {
		if x, ok := x.PacketType.(*ClientStream_ImageTransfer); ok {
			return x.ImageTransfer
		}
	}
	return nil
}

type isClientStream_PacketType interface {
	isClientStream_PacketType()
}

type ClientStream_Signal struct {
	Signal *Signal `protobuf:"bytes,2,opt,name=signal,proto3,oneof"`
}

type ClientStream_Command struct {
	Command *Run `protobuf:"bytes,3,opt,name=command,proto3,oneof"`
}

type ClientStream_BuildTransfer struct {
	BuildTransfer *BuildTransfer `protobuf:"bytes,4,opt,name=build_transfer,json=buildTransfer,proto3,oneof"`
}

type ClientStream_ImageTransfer struct {
	ImageTransfer *ImageTransfer `protobuf:"bytes,5,opt,name=image_transfer,json=imageTransfer,proto3,oneof"`
}

func (*ClientStream_Signal) isClientStream_PacketType() {}

func (*ClientStream_Command) isClientStream_PacketType() {}

func (*ClientStream_BuildTransfer) isClientStream_PacketType() {}

func (*ClientStream_ImageTransfer) isClientStream_PacketType() {}

type Signal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A POSIX signal to send to the build process.
	// Can be used for cancelling builds.
	Signal        int32 `protobuf:"varint,1,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_Builder_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_Builder_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_Builder_proto_rawDescGZIP(), []int{7}
}

func (x *Signal) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

type Run struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique ID for the execution.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The type of command to execute.
	Command       string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Run) Reset() {
	*x = Run{}
	mi := &file_Builder_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_Builder_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_Builder_proto_rawDescGZIP(), []int{8}
}

func (x *Run) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Run) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type RunComplete struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique ID for the execution.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunComplete) Reset() {
	*x = RunComplete{}
	mi := &file_Builder_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunComplete) ProtoMessage() {}

func (x *RunComplete) ProtoReflect() protoreflect.Message {
	mi := &file_Builder_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunComplete.ProtoReflect.Descriptor instead.
func (*RunComplete) Descriptor() ([]byte, []int) {
	return file_Builder_proto_rawDescGZIP(), []int{9}
}

func (x *RunComplete) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BuildTransfer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique ID for the transfer.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The direction for transferring data (either to the server or from the
	// server).
	Direction TransferDirection `protobuf:"varint,2,opt,name=direction,proto3,enum=com.apple.container.build.v1.TransferDirection" json:"direction,omitempty"`
	// The absolute path to the source from the server perspective.
	Source *string `protobuf:"bytes,3,opt,name=source,proto3,oneof" json:"source,omitempty"`
	// The absolute path for the destination from the server perspective.
	Destination *string `protobuf:"bytes,4,opt,name=destination,proto3,oneof" json:"destination,omitempty"`
	// The actual data bytes to be transferred.
	Data []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	// Signal to indicate that the transfer of data for the request has finished.
	Complete bool `protobuf:"varint,6,opt,name=complete,proto3" json:"complete,omitempty"`
	// Boolean to indicate if the content is a directory.
	IsDirectory bool `protobuf:"varint,7,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	// Metadata for the transfer.
	Metadata      map[string]string `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildTransfer) Reset() {
	*x = BuildTransfer{}
	mi := &file_Builder_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildTransfer) ProtoMessage() {}

func (x *BuildTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_Builder_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildTransfer.ProtoReflect.Descriptor instead.
func (*BuildTransfer) Descriptor() ([]byte, []int) {
	return file_Builder_proto_rawDescGZIP(), []int{10}
}

func (x *BuildTransfer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BuildTransfer) GetDirection() TransferDirection {
	if x != nil {
		return x.Direction
	}
	return TransferDirection_INTO
}

func (x *BuildTransfer) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *BuildTransfer) GetDestination() string {
	if x != nil && x.Destination != nil {
		return *x.Destination
	}
	return ""
}

func (x *BuildTransfer) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BuildTransfer) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *BuildTransfer) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

func (x *BuildTransfer) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ImageTransfer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique ID for the transfer.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The direction for transferring data (either to the server or from the
	// server).
	Direction TransferDirection `protobuf:"varint,2,opt,name=direction,proto3,enum=com.apple.container.build.v1.TransferDirection" json:"direction,omitempty"`
	// The tag for the image.
	Tag string `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	// The descriptor for the image content.
	Descriptor_ *Descriptor `protobuf:"bytes,4,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	// The actual data bytes to be transferred.
	Data []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	// Signal to indicate that the transfer of data for the request has finished.
	Complete bool `protobuf:"varint,6,opt,name=complete,proto3" json:"complete,omitempty"`
	// Metadata for the image.
	Metadata      map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageTransfer) Reset() {
	*x = ImageTransfer{}
	mi := &file_Builder_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageTransfer) ProtoMessage() {}

func (x *ImageTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_Builder_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageTransfer.ProtoReflect.Descriptor instead.
func (*ImageTransfer) Descriptor() ([]byte, []int) {
	return file_Builder_proto_rawDescGZIP(), []int{11}
}

func (x *ImageTransfer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageTransfer) GetDirection() TransferDirection {
	if x != nil {
		return x.Direction
	}
	return TransferDirection_INTO
}

func (x *ImageTransfer) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ImageTransfer) GetDescriptor_() *Descriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *ImageTransfer) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ImageTransfer) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *ImageTransfer) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ServerStream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A unique ID for the build.
	BuildId string `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	// The packet type.
	//
	// Types that are valid to be assigned to PacketType:
	//
	//	*ServerStream_Io
	//	*ServerStream_BuildError
	//	*ServerStream_CommandComplete
	//	*ServerStream_BuildTransfer
	//	*ServerStream_ImageTransfer
	PacketType    isServerStream_PacketType `protobuf_oneof:"packet_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStream) Reset() {
	*x = ServerStream{}
	mi := &file_Builder_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStream) ProtoMessage() {}

func (x *ServerStream) ProtoReflect() protoreflect.Message {
	mi := &file_Builder_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStream.ProtoReflect.Descriptor instead.
func (*ServerStream) Descriptor() ([]byte, []int) {
	return file_Builder_proto_rawDescGZIP(), []int{12}
}

func (x *ServerStream) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *ServerStream) GetPacketType() isServerStream_PacketType {
	if x != nil {
		return x.PacketType
	}
	return nil
}

func (x *ServerStream) GetIo() *IO {
	if x != nil {
		if x, ok := x.PacketType.(*ServerStream_Io); ok {
			return x.Io
		}
	}
	return nil
}

func (x *ServerStream) GetBuildError() *BuildError {
	if x != nil {
		if x, ok := x.PacketType.(*ServerStream_BuildError); ok {
			return x.BuildError
		}
	}
	return nil
}

func (x *ServerStream) GetCommandComplete() *RunComplete {
	if x != nil {
		if x, ok := x.PacketType.(*ServerStream_CommandComplete); ok {
			return x.CommandComplete
		}
	}
	return nil
}

func (x *ServerStream) GetBuildTransfer() *BuildTransfer {
	if x != nil {
		if x, ok := x.PacketType.(*ServerStream_BuildTransfer); ok {
			return x.BuildTransfer
		}
	}
	return nil
}

func (x *ServerStream) GetImageTransfer() *ImageTransfer {
	if x != nil {
		if x, ok := x.PacketType.(*ServerStream_ImageTransfer); ok {
			return x.ImageTransfer
		}
	}
	return nil
}

type isServerStream_PacketType interface {
	isServerStream_PacketType()
}

type ServerStream_Io struct {
	Io *IO `protobuf:"bytes,2,opt,name=io,proto3,oneof"`
}

type ServerStream_BuildError struct {
	BuildError *BuildError `protobuf:"bytes,3,opt,name=build_error,json=buildError,proto3,oneof"`
}

type ServerStream_CommandComplete struct {
	CommandComplete *RunComplete `protobuf:"bytes,4,opt,name=command_complete,json=commandComplete,proto3,oneof"`
}

type ServerStream_BuildTransfer struct {
	BuildTransfer *BuildTransfer `protobuf:"bytes,5,opt,name=build_transfer,json=buildTransfer,proto3,oneof"`
}

type ServerStream_ImageTransfer struct {
	ImageTransfer *ImageTransfer `protobuf:"bytes,6,opt,name=image_transfer,json=imageTransfer,proto3,oneof"`
}

func (*ServerStream_Io) isServerStream_PacketType() {}

func (*ServerStream_BuildError) isServerStream_PacketType() {}

func (*ServerStream_CommandComplete) isServerStream_PacketType() {}

func (*ServerStream_BuildTransfer) isServerStream_PacketType() {}

func (*ServerStream_ImageTransfer) isServerStream_PacketType() {}

type IO struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of IO.
	Type Stdio `protobuf:"varint,1,opt,name=type,proto3,enum=com.apple.container.build.v1.Stdio" json:"type,omitempty"`
	// The IO data bytes.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IO) Reset() {
	*x = IO{}
	mi := &file_Builder_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IO) ProtoMessage() {}

func (x *IO) ProtoReflect() protoreflect.Message {
	mi := &file_Builder_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IO.ProtoReflect.Descriptor instead.
func (*IO) Descriptor() ([]byte, []int) {
	return file_Builder_proto_rawDescGZIP(), []int{13}
}

func (x *IO) GetType() Stdio {
	if x != nil {
		return x.Type
	}
	return Stdio_STDIN
}

func (x *IO) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BuildError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of build error.
	Type BuildErrorType `protobuf:"varint,1,opt,name=type,proto3,enum=com.apple.container.build.v1.BuildErrorType" json:"type,omitempty"`
	// Additional message for the build failure.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildError) Reset() {
	*x = BuildError{}
	mi := &file_Builder_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildError) ProtoMessage() {}

func (x *BuildError) ProtoReflect() protoreflect.Message {
	mi := &file_Builder_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildError.ProtoReflect.Descriptor instead.
func (*BuildError) Descriptor() ([]byte, []int) {
	return file_Builder_proto_rawDescGZIP(), []int{14}
}

func (x *BuildError) GetType() BuildErrorType {
	if x != nil {
		return x.Type
	}
	return BuildErrorType_BUILD_FAILED
}

func (x *BuildError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// OCI Platform metadata.
type Platform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Architecture  string                 `protobuf:"bytes,1,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	OsVersion     string                 `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	OsFeatures    []string               `protobuf:"bytes,4,rep,name=os_features,json=osFeatures,proto3" json:"os_features,omitempty"`
	Variant       string                 `protobuf:"bytes,5,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Platform) Reset() {
	*x = Platform{}
	mi := &file_Builder_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Platform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Platform) ProtoMessage() {}

func (x *Platform) ProtoReflect() protoreflect.Message {
	mi := &file_Builder_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Platform.ProtoReflect.Descriptor instead.
func (*Platform) Descriptor() ([]byte, []int) {
	return file_Builder_proto_rawDescGZIP(), []int{15}
}

func (x *Platform) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *Platform) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Platform) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *Platform) GetOsFeatures() []string {
	if x != nil {
		return x.OsFeatures
	}
	return nil
}

func (x *Platform) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

// OCI Descriptor metadata.
type Descriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaType     string                 `protobuf:"bytes,1,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Urls          []string               `protobuf:"bytes,4,rep,name=urls,proto3" json:"urls,omitempty"`
	Annotations   map[string]string      `protobuf:"bytes,5,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Platform      *Platform              `protobuf:"bytes,6,opt,name=platform,proto3,oneof" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Descriptor) Reset() {
	*x = Descriptor{}
	mi := &file_Builder_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Descriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Descriptor) ProtoMessage() {}

func (x *Descriptor) ProtoReflect() protoreflect.Message {
	mi := &file_Builder_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Descriptor.ProtoReflect.Descriptor instead.
func (*Descriptor) Descriptor() ([]byte, []int) {
	return file_Builder_proto_rawDescGZIP(), []int{16}
}

func (x *Descriptor) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *Descriptor) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *Descriptor) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Descriptor) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *Descriptor) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Descriptor) GetPlatform() *Platform {
	if x != nil {
		return x.Platform
	}
	return nil
}

var File_Builder_proto protoreflect.FileDescriptor

const file_Builder_proto_rawDesc = "" +
	"\n" +
	"\rBuilder.proto\x12\x1ccom.apple.container.build.v1\"\r\n" +
	"\vInfoRequest\"\x0e\n" +
	"\fInfoResponse\".\n" +
	"\x14LookupContextRequest\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\"1\n" +
	"\x15LookupContextResponse\x12\x18\n" +
	"\apresent\x18\x01 \x01(\bR\apresent\"\x93\x02\n" +
	"\x12CreateBuildRequest\x12\x1d\n" +
	"\n" +
	"stage_name\x18\x01 \x01(\tR\tstageName\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12Z\n" +
	"\bmetadata\x18\x03 \x03(\v2>.com.apple.container.build.v1.CreateBuildRequest.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"build_args\x18\x04 \x03(\tR\tbuildArgs\x12\x14\n" +
	"\x05debug\x18\x05 \x01(\bR\x05debug\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xca\x01\n" +
	"\x13CreateBuildResponse\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12[\n" +
	"\bmetadata\x18\x02 \x03(\v2?.com.apple.container.build.v1.CreateBuildResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe3\x02\n" +
	"\fClientStream\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12>\n" +
	"\x06signal\x18\x02 \x01(\v2$.com.apple.container.build.v1.SignalH\x00R\x06signal\x12=\n" +
	"\acommand\x18\x03 \x01(\v2!.com.apple.container.build.v1.RunH\x00R\acommand\x12T\n" +
	"\x0ebuild_transfer\x18\x04 \x01(\v2+.com.apple.container.build.v1.BuildTransferH\x00R\rbuildTransfer\x12T\n" +
	"\x0eimage_transfer\x18\x05 \x01(\v2+.com.apple.container.build.v1.ImageTransferH\x00R\rimageTransferB\r\n" +
	"\vpacket_type\" \n" +
	"\x06Signal\x12\x16\n" +
	"\x06signal\x18\x01 \x01(\x05R\x06signal\"/\n" +
	"\x03Run\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\"\x1d\n" +
	"\vRunComplete\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb4\x03\n" +
	"\rBuildTransfer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12M\n" +
	"\tdirection\x18\x02 \x01(\x0e2/.com.apple.container.build.v1.TransferDirectionR\tdirection\x12\x1b\n" +
	"\x06source\x18\x03 \x01(\tH\x00R\x06source\x88\x01\x01\x12%\n" +
	"\vdestination\x18\x04 \x01(\tH\x01R\vdestination\x88\x01\x01\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x1a\n" +
	"\bcomplete\x18\x06 \x01(\bR\bcomplete\x12!\n" +
	"\fis_directory\x18\a \x01(\bR\visDirectory\x12U\n" +
	"\bmetadata\x18\b \x03(\v29.com.apple.container.build.v1.BuildTransfer.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\a_sourceB\x0e\n" +
	"\f_destination\"\x8e\x03\n" +
	"\rImageTransfer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12M\n" +
	"\tdirection\x18\x02 \x01(\x0e2/.com.apple.container.build.v1.TransferDirectionR\tdirection\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12H\n" +
	"\n" +
	"descriptor\x18\x04 \x01(\v2(.com.apple.container.build.v1.DescriptorR\n" +
	"descriptor\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x1a\n" +
	"\bcomplete\x18\x06 \x01(\bR\bcomplete\x12U\n" +
	"\bmetadata\x18\a \x03(\v29.com.apple.container.build.v1.ImageTransfer.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x03\n" +
	"\fServerStream\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x122\n" +
	"\x02io\x18\x02 \x01(\v2 .com.apple.container.build.v1.IOH\x00R\x02io\x12K\n" +
	"\vbuild_error\x18\x03 \x01(\v2(.com.apple.container.build.v1.BuildErrorH\x00R\n" +
	"buildError\x12V\n" +
	"\x10command_complete\x18\x04 \x01(\v2).com.apple.container.build.v1.RunCompleteH\x00R\x0fcommandComplete\x12T\n" +
	"\x0ebuild_transfer\x18\x05 \x01(\v2+.com.apple.container.build.v1.BuildTransferH\x00R\rbuildTransfer\x12T\n" +
	"\x0eimage_transfer\x18\x06 \x01(\v2+.com.apple.container.build.v1.ImageTransferH\x00R\rimageTransferB\r\n" +
	"\vpacket_type\"Q\n" +
	"\x02IO\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.com.apple.container.build.v1.StdioR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"h\n" +
	"\n" +
	"BuildError\x12@\n" +
	"\x04type\x18\x01 \x01(\x0e2,.com.apple.container.build.v1.BuildErrorTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x98\x01\n" +
	"\bPlatform\x12\"\n" +
	"\farchitecture\x18\x01 \x01(\tR\farchitecture\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x03 \x01(\tR\tosVersion\x12\x1f\n" +
	"\vos_features\x18\x04 \x03(\tR\n" +
	"osFeatures\x12\x18\n" +
	"\avariant\x18\x05 \x01(\tR\avariant\"\xde\x02\n" +
	"\n" +
	"Descriptor\x12\x1d\n" +
	"\n" +
	"media_type\x18\x01 \x01(\tR\tmediaType\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04urls\x18\x04 \x03(\tR\x04urls\x12[\n" +
	"\vannotations\x18\x05 \x03(\v29.com.apple.container.build.v1.Descriptor.AnnotationsEntryR\vannotations\x12G\n" +
	"\bplatform\x18\x06 \x01(\v2&.com.apple.container.build.v1.PlatformH\x00R\bplatform\x88\x01\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\v\n" +
	"\t_platform*(\n" +
	"\x11TransferDirection\x12\b\n" +
	"\x04INTO\x10\x00\x12\t\n" +
	"\x05OUTOF\x10\x01**\n" +
	"\x05Stdio\x12\t\n" +
	"\x05STDIN\x10\x00\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x01\x12\n" +
	"\n" +
	"\x06STDERR\x10\x02*0\n" +
	"\x0eBuildErrorType\x12\x10\n" +
	"\fBUILD_FAILED\x10\x00\x12\f\n" +
	"\bINTERNAL\x10\x012\xc2\x03\n" +
	"\aBuilder\x12r\n" +
	"\vCreateBuild\x120.com.apple.container.build.v1.CreateBuildRequest\x1a1.com.apple.container.build.v1.CreateBuildResponse\x12j\n" +
	"\fPerformBuild\x12*.com.apple.container.build.v1.ClientStream\x1a*.com.apple.container.build.v1.ServerStream(\x010\x01\x12]\n" +
	"\x04Info\x12).com.apple.container.build.v1.InfoRequest\x1a*.com.apple.container.build.v1.InfoResponse\x12x\n" +
	"\rLookupContext\x122.com.apple.container.build.v1.LookupContextRequest\x1a3.com.apple.container.build.v1.LookupContextResponseB\rZ\vpkg/api;apib\x06proto3"

var (
	file_Builder_proto_rawDescOnce sync.Once
	file_Builder_proto_rawDescData []byte
)

func file_Builder_proto_rawDescGZIP() []byte {
	file_Builder_proto_rawDescOnce.Do(func() {
		file_Builder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Builder_proto_rawDesc), len(file_Builder_proto_rawDesc)))
	})
	return file_Builder_proto_rawDescData
}

var file_Builder_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_Builder_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_Builder_proto_goTypes = []any{
	(TransferDirection)(0),        // 0: com.apple.container.build.v1.TransferDirection
	(Stdio)(0),                    // 1: com.apple.container.build.v1.Stdio
	(BuildErrorType)(0),           // 2: com.apple.container.build.v1.BuildErrorType
	(*InfoRequest)(nil),           // 3: com.apple.container.build.v1.InfoRequest
	(*InfoResponse)(nil),          // 4: com.apple.container.build.v1.InfoResponse
	(*LookupContextRequest)(nil),  // 5: com.apple.container.build.v1.LookupContextRequest
	(*LookupContextResponse)(nil), // 6: com.apple.container.build.v1.LookupContextResponse
	(*CreateBuildRequest)(nil),    // 7: com.apple.container.build.v1.CreateBuildRequest
	(*CreateBuildResponse)(nil),   // 8: com.apple.container.build.v1.CreateBuildResponse
	(*ClientStream)(nil),          // 9: com.apple.container.build.v1.ClientStream
	(*Signal)(nil),                // 10: com.apple.container.build.v1.Signal
	(*Run)(nil),                   // 11: com.apple.container.build.v1.Run
	(*RunComplete)(nil),           // 12: com.apple.container.build.v1.RunComplete
	(*BuildTransfer)(nil),         // 13: com.apple.container.build.v1.BuildTransfer
	(*ImageTransfer)(nil),         // 14: com.apple.container.build.v1.ImageTransfer
	(*ServerStream)(nil),          // 15: com.apple.container.build.v1.ServerStream
	(*IO)(nil),                    // 16: com.apple.container.build.v1.IO
	(*BuildError)(nil),            // 17: com.apple.container.build.v1.BuildError
	(*Platform)(nil),              // 18: com.apple.container.build.v1.Platform
	(*Descriptor)(nil),            // 19: com.apple.container.build.v1.Descriptor
	nil,                           // 20: com.apple.container.build.v1.CreateBuildRequest.MetadataEntry
	nil,                           // 21: com.apple.container.build.v1.CreateBuildResponse.MetadataEntry
	nil,                           // 22: com.apple.container.build.v1.BuildTransfer.MetadataEntry
	nil,                           // 23: com.apple.container.build.v1.ImageTransfer.MetadataEntry
	nil,                           // 24: com.apple.container.build.v1.Descriptor.AnnotationsEntry
}
var file_Builder_proto_depIdxs = []int32{
	20, // 0: com.apple.container.build.v1.CreateBuildRequest.metadata:type_name -> com.apple.container.build.v1.CreateBuildRequest.MetadataEntry
	21, // 1: com.apple.container.build.v1.CreateBuildResponse.metadata:type_name -> com.apple.container.build.v1.CreateBuildResponse.MetadataEntry
	10, // 2: com.apple.container.build.v1.ClientStream.signal:type_name -> com.apple.container.build.v1.Signal
	11, // 3: com.apple.container.build.v1.ClientStream.command:type_name -> com.apple.container.build.v1.Run
	13, // 4: com.apple.container.build.v1.ClientStream.build_transfer:type_name -> com.apple.container.build.v1.BuildTransfer
	14, // 5: com.apple.container.build.v1.ClientStream.image_transfer:type_name -> com.apple.container.build.v1.ImageTransfer
	0,  // 6: com.apple.container.build.v1.BuildTransfer.direction:type_name -> com.apple.container.build.v1.TransferDirection
	22, // 7: com.apple.container.build.v1.BuildTransfer.metadata:type_name -> com.apple.container.build.v1.BuildTransfer.MetadataEntry
	0,  // 8: com.apple.container.build.v1.ImageTransfer.direction:type_name -> com.apple.container.build.v1.TransferDirection
	19, // 9: com.apple.container.build.v1.ImageTransfer.descriptor:type_name -> com.apple.container.build.v1.Descriptor
	23, // 10: com.apple.container.build.v1.ImageTransfer.metadata:type_name -> com.apple.container.build.v1.ImageTransfer.MetadataEntry
	16, // 11: com.apple.container.build.v1.ServerStream.io:type_name -> com.apple.container.build.v1.IO
	17, // 12: com.apple.container.build.v1.ServerStream.build_error:type_name -> com.apple.container.build.v1.BuildError
	12, // 13: com.apple.container.build.v1.ServerStream.command_complete:type_name -> com.apple.container.build.v1.RunComplete
	13, // 14: com.apple.container.build.v1.ServerStream.build_transfer:type_name -> com.apple.container.build.v1.BuildTransfer
	14, // 15: com.apple.container.build.v1.ServerStream.image_transfer:type_name -> com.apple.container.build.v1.ImageTransfer
	1,  // 16: com.apple.container.build.v1.IO.type:type_name -> com.apple.container.build.v1.Stdio
	2,  // 17: com.apple.container.build.v1.BuildError.type:type_name -> com.apple.container.build.v1.BuildErrorType
	24, // 18: com.apple.container.build.v1.Descriptor.annotations:type_name -> com.apple.container.build.v1.Descriptor.AnnotationsEntry
	18, // 19: com.apple.container.build.v1.Descriptor.platform:type_name -> com.apple.container.build.v1.Platform
	7,  // 20: com.apple.container.build.v1.Builder.CreateBuild:input_type -> com.apple.container.build.v1.CreateBuildRequest
	9,  // 21: com.apple.container.build.v1.Builder.PerformBuild:input_type -> com.apple.container.build.v1.ClientStream
	3,  // 22: com.apple.container.build.v1.Builder.Info:input_type -> com.apple.container.build.v1.InfoRequest
	5,  // 23: com.apple.container.build.v1.Builder.LookupContext:input_type -> com.apple.container.build.v1.LookupContextRequest
	8,  // 24: com.apple.container.build.v1.Builder.CreateBuild:output_type -> com.apple.container.build.v1.CreateBuildResponse
	15, // 25: com.apple.container.build.v1.Builder.PerformBuild:output_type -> com.apple.container.build.v1.ServerStream
	4,  // 26: com.apple.container.build.v1.Builder.Info:output_type -> com.apple.container.build.v1.InfoResponse
	6,  // 27: com.apple.container.build.v1.Builder.LookupContext:output_type -> com.apple.container.build.v1.LookupContextResponse
	24, // [24:28] is the sub-list for method output_type
	20, // [20:24] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_Builder_proto_init() }
func file_Builder_proto_init() {
	if File_Builder_proto != nil {
		return
	}
	file_Builder_proto_msgTypes[6].OneofWrappers = []any{
		(*ClientStream_Signal)(nil),
		(*ClientStream_Command)(nil),
		(*ClientStream_BuildTransfer)(nil),
		(*ClientStream_ImageTransfer)(nil),
	}
	file_Builder_proto_msgTypes[10].OneofWrappers = []any{}
	file_Builder_proto_msgTypes[12].OneofWrappers = []any{
		(*ServerStream_Io)(nil),
		(*ServerStream_BuildError)(nil),
		(*ServerStream_CommandComplete)(nil),
		(*ServerStream_BuildTransfer)(nil),
		(*ServerStream_ImageTransfer)(nil),
	}
	file_Builder_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Builder_proto_rawDesc), len(file_Builder_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Builder_proto_goTypes,
		DependencyIndexes: file_Builder_proto_depIdxs,
		EnumInfos:         file_Builder_proto_enumTypes,
		MessageInfos:      file_Builder_proto_msgTypes,
	}.Build()
	File_Builder_proto = out.File
	file_Builder_proto_goTypes = nil
	file_Builder_proto_depIdxs = nil
}
