name: Container Builder Shim - common jobs

permissions:
  contents: read

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps: 
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: '1.25.5'
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
      - name: Check formatting
        run: | 
          ./scripts/install-hawkeye.sh
          make fmt
          git diff
          if ! git diff --quiet ; then echo the following files require formatting or license headers: ; git diff --name-only ; false ; fi
      - name: Check dependencies 
        run: |
          go mod tidy 
          go mod vendor
          git add --all --intent-to-add .
          if ! git diff --quiet ; then echo Please run `go mod tidy && go mod vendor`. Out of date dependency files: ; git diff --name-only ; false ; fi
      - name: Check protobufs 
        run: | 
          make go-protos
          if ! git diff --quiet ; then echo the following files require formatting or license headers: ; git diff --name-only ; false ; fi
      - name: Build
        run: |
          make build
      - name: Test
        run: |
          make test
